name: Publish artefacts

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make RELEASE=true
      - uses: actions/upload-artifact@v3
        with:
          name: labyrinth_linux
          path: |
            build/labyrinth

  macOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make RELEASE=true
      - uses: actions/upload-artifact@v3
        with:
          name: labyrinth_macos
          path: |
            build/labyrinth
