name: Publish artefacts

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make RELEASE=true
      - name: Pack
        run: cd ./build/ && tar -czf labyrinth_linux64.tar.gz  ./labyrinth
      - uses: actions/upload-artifact@v3
        with:
          name: labyrinth_linux64.tar.gz
          path: build/labyrinth_linux64.tar.gz

  macOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make RELEASE=true
      - name: Pack
        run: cd ./build/ && tar -czf labyrinth_macos.tar.gz  ./labyrinth
      - uses: actions/upload-artifact@v3
        with:
          name: labyrinth_macos.tar.gz
          path: build/labyrinth_macos.tar.gz
